name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [ '16', '14' ]
    name: Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm install
      - name: test
        run: npm test

  build_latest:
    name: Node latest
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: test
        run: npm test
